# Generated by Django 6.0.2 on 2026-03-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "prodid",
                    models.CharField(
                        blank=True,
                        help_text="Falls back to settings.ICALENDAR_PRODID or '-//django-icalendar//django-icalendar//EN'.",
                        max_length=255,
                        verbose_name="product ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="CSS3 color name or hex value, e.g. 'tomato' or '#FF6347'.",
                        max_length=50,
                        verbose_name="color",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="iTIP method (RFC 5546): PUBLISH, REQUEST, REPLY, etc.",
                        max_length=30,
                        verbose_name="method",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar",
                "verbose_name_plural": "Calendars",
            },
        ),
    ]
