# Changes here will be overwritten by Copier
_commit: d360da4
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: true
copyright_year: '2026'
django_app_shorthand: django_icalendar
documentation: true
email: abe@habet.dev
full_name: abe hanoka
github_username: mergecal
has_cli: false
initial_commit: true
is_django_package: true
open_source_license: GPL-3.0-only
open_with_editor: true
package_name: django_icalendar
project_name: Django icalendar
project_short_description: Django models for storing and exporting RFC 5545 iCalendar
    data.
project_slug: django-icalendar
run_uv_sync: true
setup_github: true
setup_pre_commit: true

